### ISSUE TITLE
pelion-edge.relay-term log output error: Unable to read from config file 

### ISSUE THREAD

**Issue by LingfeiXie** [LingfeiXie/Snap-Pelion-Edge-Test#1]
I built pelion-edge_1.18.1_amd64.snap and run it on Ubuntu 18.04(LTS)

Pelion-edge Active process shows below:
```
services:
  pelion-edge.dockerd:    simple, enabled, inactive
  pelion-edge.edge-core:  simple, enabled, active
  pelion-edge.edge-proxy: simple, enabled, active
  pelion-edge.identity:   simple, enabled, active
  pelion-edge.kubelet:    simple, enabled, inactive
  pelion-edge.maestro:    simple, enabled, active
  pelion-edge.relay-term: simple, enabled, active
``` 

pelion-edge.relay-term logs  gives following error

```
Execute Command: sudo snap logs -n=all pelion-edge.relay-term 
Output : 2020-09-30T04:50:34Z pelion-edge.relay-term[25324]: Error: Unable to read from config file at: /var/snap/pelion-edge/x1/wigwag/etc/relayterm-config.json
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]: at loadConfig (/snap/pelion-edge/x1/wigwag/wigwag-core-modules/relay-term/src/commands/start.js:53:15)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]: at execute (/snap/pelion-edge/x1/wigwag/wigwag-core-modules/relay-term/src/commands/start.js:104:18)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]: at run (/snap/pelion-edge/x1/wigwag/wigwag-core-modules/relay-term/src/index.js:47:23)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]:     at Object.<anonymous> (/snap/pelion-edge/x1/wigwag/wigwag-core-modules/relay-term/src/index.js:50:1)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]:     at Module._compile (module.js:653:30)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]:     at Object.Module._extensions..js (module.js:664:10)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]:     at Module.load (module.js:566:32)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]:     at tryModuleLoad (module.js:506:12)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]:     at Function.Module._load (module.js:498:3)
2020-09-30T04:50:34Z pelion-edge.relay-term[25324]:     at Function.Module.runMain (module.js:694:10)
```

**Environment**
・OS( from /etc/os-release)
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
・Architecture
```
x86_64
```

**UPDATE**
After execute the following commands, Service **pelion-edge.kubelet** and **pelion-edge.dockerd** become active

```
services:
  pelion-edge.devicedb:   simple, disabled, inactive
  pelion-edge.dockerd:    simple, enabled, active
  pelion-edge.edge-core:  simple, enabled, active
  pelion-edge.edge-proxy: simple, enabled, active
  pelion-edge.identity:   simple, enabled, inactive
  pelion-edge.kubelet:    simple, enabled, active
  pelion-edge.maestro:    simple, enabled, active
  pelion-edge.relay-term: simple, enabled, active
```
->When installing on Ubuntu 18.04 server do the following<-
```
sudo snap install network-manager
sudo snap install modem-manager
```
After Executed the following scripts, pelion-edge.relay-term log output stop giving the error. 
->Hookup the following connections<-
```
sudo snap connect pelion-edge:snapd-control :snapd-control
sudo snap connect pelion-edge:modem-manager modem-manager:service
sudo snap connect pelion-edge:network-manager network-manager:service
sudo snap connect pelion-edge:network-control :network-control
sudo snap connect pelion-edge:privileged :docker-support
sudo snap connect pelion-edge:support :docker-support
sudo snap connect pelion-edge:firewall-control :firewall-control
sudo snap connect pelion-edge:docker-cli pelion-edge:docker-daemon
sudo snap connect pelion-edge:log-observe :log-observe
sudo snap connect pelion-edge:system-files-logs :system-files
sudo snap connect pelion-edge:kernel-module-observe :kernel-module-observe
sudo snap connect pelion-edge:system-trace :system-trace
sudo snap connect pelion-edge:system-observe :system-observe
sudo snap connect pelion-edge:account-control :account-control
sudo snap connect pelion-edge:bluetooth-control :bluetooth-control
sudo snap connect pelion-edge:hardware-observe :hardware-observe
sudo snap connect pelion-edge:kubernetes-support :kubernetes-support
sudo snap connect pelion-edge:mount-observe :mount-observe
sudo snap connect pelion-edge:netlink-audit :netlink-audit
sudo snap connect pelion-edge:netlink-connector :netlink-connector
sudo snap connect pelion-edge:network-observe :network-observe
sudo snap connect pelion-edge:process-control :process-control
sudo snap connect pelion-edge:shutdown :shutdown
```

**Comment by LingfeiXie** [comment]
Show active process command
$snap info pelion-edge

services:
  pelion-edge.devicedb:   simple, disabled, inactive
  pelion-edge.dockerd:    simple, enabled, active
  pelion-edge.edge-core:  simple, enabled, active
  pelion-edge.edge-proxy: simple, enabled, active
  pelion-edge.identity:   simple, enabled, inactive
  pelion-edge.kubelet:    simple, enabled, active
  pelion-edge.maestro:    simple, enabled, active
  pelion-edge.relay-term: simple, enabled, active
